services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - meu-portfolio-front-network

networks:
  meu-portfolio-front-network:
    driver: bridge
