import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfólio",
  description: "Generated by André Campos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
    </html>
  );
}
